config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'account_roles_accounts', to: 'account_roles#accounts'
  get 'rights', to: 'account_roles#rights'
  get 'account_roles', to: 'account_roles#account_roles'

  namespace :manage do
    namespace :settings do
      namespace :acl2 do
        resources :account_roles do
          member do
            get :rights
            put :update_rights
            get :save_role

            get :users
            put :update_users
          end
        end
      end
    end
  end

  root "account_roles#welcome"
end

app/models/account_role.rb
class AccountRole < ApplicationRecord
  belongs_to :account
end

app/controllers/account_roles_controller.rb
class AccountRolesController < ApplicationController
  before_action :find_account, except: [:welcome, :accounts, :accounts_show, :index ]

  def welcome
    
  end

  def accounts
    @accounts = current_user.accounts
  end

  def accounts_show
        
  end

  def account_roles
    @account_roles = AccountRole.all
  end

  def index
    @account_roles = current_account.account_roles
  end

  def new
    @account_role = current_account.account_roles.new
  end

  def create
    @account_role = current_account.account_roles.new(account_role_params)
    if @account_role.save
      flash[:notice] = 'Role created.'
      redirect_to manage_settings_acl2_account_roles_path
    else
      render :new
    end
  end

  def update
    @account_role = current_account.account_roles.find params[:id]
    @account_role.update_attributes account_role_params
    flash[:notice] = 'Role updated'
    redirect_to manage_settings_acl2_account_roles_path
  end

  def edit
    @account_role = current_account.account_roles.find params[:id]
  end

  def destroy
    @account_role = @account.account_roles.find params[:id]
    current_account.account_roles.delete(@account_role)
    flash[:notice] = 'Role removed.'
    redirect_to manage_settings_acl2_account_roles_path
  end

  def rights
    @account_role = @account.account_roles.find params[:id]
  end

  def update_rights
    save_role
    @account_role = @account.account_roles.find params[:id]
    params[:right_ids].each do |right_id, result|
      if result.to_s=='true'
        AccountRoleRight.find_or_create_by(right_id: right_id, account_role_id: params[:id])
      else
        AccountRoleRight.where(right_id: right_id, account_role_id: params[:id]).delete_all
      end
    end
    flash[:notice] = 'Rights updated.'
    redirect_to manage_settings_acl2_account_roles_path
  end

  def users
    @account_role = current_account.account_roles.find params[:id]
  end

  def update_users
    @account_role = current_account.account_roles.find params[:id]
    params[:user_ids].each do |user_id, result|
      if result.to_s=='true'
        UserAccountRole.find_or_create_by(user_id: user_id, account_role_id: params[:id])
      else
        UserAccountRole.where(user_id: user_id, account_role_id: params[:id]).delete_all
      end
    end
    flash[:notice] = 'Users updated.'
    redirect_to manage_settings_acl2_account_roles_path
  end

  def save_role
    binding.pry
    if params[:gb_admin_role][:role].count == 1
      GbAdminRole.create! user_id: @account.user.id, role: params[:gb_admin_role][:role].first
      redirect_to account_roles_accounts_path
    elsif params[:gb_admin_role][:role].count == 2
      GbAdminRole.create! user_id: @account.user.id, role: "ROLE_ADMIN"
      redirect_to account_roles_accounts_path
    else
      redirect_to account_roles_accounts_path
    end
  end

  private

    def account_role_params
      params.require(:account_role).permit(:name, :description)
    end

    def find_account
      @account = AccountRole.find(params[:id]).account
    end
end

app/helpers/account_roles_helper.rb
module AccountRolesHelper
end

app/views/account_roles/accounts.html.erb
<div class="flash_messages">
  <% unless flash.nil? %>
    <% flash.each do |type, message| %>
      <% if type == :success %>
        <% alert_type = 'alert-success' %>
      <% elsif type == :error %>
        <% alert_type = 'alert-error' %>
      <% else %>
        <% alert_type = 'alert-info' %>
      <% end %>
      <div class="alert <%= alert_type %> fade in no-margin">
        <%= message %>
      </div>
    <% end %>
  <% end %>
</div>


<% if @accounts.present? %>
  <% @accounts.each do |acc| %>
    <label>User Name: </label>
    <%= acc.user.username %>
    <label>Account Name: </label>
      <%= acc.name %>
    <% if acc.account_roles.present? %>
      <label>Account Role Name: </label>
      <% acc.account_roles.each do |account_role| %>
        <%= link_to rights_path(id: account_role.id) do %>
          <%= account_role.name %>
        <% end %>
      <% end %>
      <br>
    <% end %>
    <br>
  <% end %>
<% end %>

app/views/account_roles/rights.html.erb
<!-- @account = current_account -->
<%= form_tag(update_rights_manage_settings_acl2_account_role_path(@account_role),:method => 'put', :class => 'form-signin') do %>
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-8">
      <h2>Roles and Rights</h2>
      <ol class="breadcrumb">
        <li>
          <!-- no route avaible manage_root_path -->
          <a href="<%#= manage_root_path %>"><%= t('labels.modules.home') %></a>
        </li>
        <li class="active">
          <!-- no route avaible manage_settings_acl2_account_roles_path -->
          <a href="<%#= manage_settings_acl2_account_roles_path%>">Roles</a>
        </li>
        <li>
          <%= @account_role.name %>
        </li>
        <li class="active">
          <strong>Rights</strong>
        </li>
      </ol>
    </div>
    <div class="col-lg-4">
      <div class="title-action">
        <a class="btn btn-default" onclick="$('input:checkbox').iCheck('uncheck');">DeselectAll</a>
        <a class="btn btn-default" onclick="$('input:checkbox').iCheck('check');">Select All</a>
        <%= submit_tag "Save", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class='wrapper wrapper-content animated fadeInRight'>
    <!-- no partials provided -->
    <%#= render :partial => "manage/layouts/notices" %>
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Deals</h5>
          </div>
        <div class="ibox-content">
          <% Right.where(category: 'deals').each do |right| %>
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <div class="checkbox i-checks">
                    <label class="">
                      <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                      <!-- no model level method given -->
                      <%= check_box_tag "right_ids[#{right.id}]", true, @account_role, class: "position: absolute; opacity: 0;" %>
                      <i></i>
                      <!-- no partials provided -->
                      <%= right.name.html_safe %>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <br>
        <div class="ibox-title">
          <h5>Blog Posts</h5>
        </div>
        <div class="ibox-content">
          <% Right.where(category: 'articles').each do |right| %>
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <div class="checkbox i-checks">
                    <label class="">
                      <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                      <!-- no model level method given -->
                      <%= check_box_tag "right_ids[#{right.id}]", true, @account_role, class: "position: absolute; opacity: 0;" %>
                      <i></i>
                      <%= right.name.html_safe %>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          <%end%>
        </div>
        <br>
        <div class="ibox-title">
          <h5>Pages and Partials</h5>
        </div>
        <div class="ibox-content">
          <% Right.where(category: 'pages').each do |right| %>
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <div class="checkbox i-checks">
                    <label class="">
                      <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                      <!-- no model level method given -->
                      <%= check_box_tag "right_ids[#{right.id}]", true, @account_role, class: "position: absolute; opacity: 0;" %>
                      <i></i>
                      <%= right.name.html_safe %>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          <%end%>
        </div>
        <br>
        <!-- no methods given -->
         <!-- current_account not accesible (@account = current_account)-->
         <!-- Assuming it to be current account -->
         <% if @account.present? %>
          <% Account.all.each do |handle| %>
            <div class="ibox-title">
              <h5><%= handle.to_s.humanize %></h5>
            </div>
            <div class="ibox-content">
              <% right = Right.where(key: "view_#{handle}").first_or_create
                right.name =  "View #{handle}"
                right.actions = 'show index'
                right.save %>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <div class="checkbox i-checks">
                      <label class="">
                        <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                        <%= check_box_tag "right_ids[#{right.id}]", true, @account_role, class: "position: absolute; opacity: 0;" %>
                        <i></i>
                        <%= right.name.html_safe %>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <%# right = Right.where(key: "manage_#{handle}", category:"#{@account.subdomain}_custom_forms").first_or_create 
                if @account.tc("manage.forms.#{handle}_has_status").present?
                  right.name = "Mark status, <b>manage #{handle}</b>"
                else
                  right.name = "<b>Manage #{handle}</b>"
                end
                right.actions ||= 'show index mark_status delete'
                right.save
              %>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <div class="checkbox i-checks">
                      <label class="">
                      <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                      <%= check_box_tag "right_ids[#{right.id}]", true, @account_role, class: "position: absolute; opacity: 0;" %>
                      <i></i>
                      <%= right.name.html_safe %>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
          <% end %>
        <% end %>
      <div class="ibox-title">
        <h5>Settings</h5>
      </div>
      <div class="ibox-content">
        <% Right.where(category: 'settings').each do |right| %>
          <div class="row">
            <div class="col-sm-12">
              <div class="form-group">
                <div class="checkbox i-checks">
                  <label class="">
                    <%= hidden_field_tag "right_ids[#{right.id}]", false %>
                    <%= check_box_tag "right_ids[#{right.id}]", true,@account_role, class: "position: absolute; opacity: 0;" %>
                    <i></i>
                    <%= right.name.html_safe %>
                  </label>
                </div>
              </div>
            </div>
          </div>
        <%end%>
      </div>

        </div>
      </div>
    </div>
  </div>

<%end%>

<div class="ibox-title">
  <h5>External Admin Tools</h5>
</div>
<div class="ibox-content">
  <div class="extername_admin_tools">
  <% User.all.each do %>

  <% end %>
    <%= form_tag(save_role_manage_settings_acl2_account_role_path(id: current_user.id), method: :get) do %>
      <%= hidden_field_tag :user, current_user.id %>
      <ul>
        <li>
          <label>Role Cache:</label>
          <%= check_box_tag("gb_admin_role[role][]", "ROLE_CACHE",false, id: "check_1") %>          
        </li>
        <li>
          <label>Managed Content:</label>
          <%= check_box_tag "gb_admin_role[role][]", "ROLE_CONTENT",false, id: "check_2"%>          
        </li>
        <li>
          <label>All:</label>
          <%= check_box_tag "All","",false, id: "check_all" %>          
        </li>
        <li>
          <%= submit_tag "Save" %>
        </li>
      </ul>
      <br>
    <% end %>
    <label>
      User Name: <%= User.find(@account.user.id).username %>
    </label>
  </div>
</div>

app/views/account_roles/welcome.html.erb
<h1>Welcome to Account Roles</h1>